woowa-techcamp-2020/todo-13

client/package-lock.json, client/package.json, client/src/index.js, client/src/style.scss, client/webpack.config.js
Webpack에 sass loader를 추가해서 sass문법으로 스타일을 작성할 수 있습니다.
=> Add sass loader in webpack config

client/src/components/Card.js, client/src/components/Card.scss, client/src/components/Column.js, client/src/components/Column.scss, client/src/components/Dashboard.js, client/src/components/Dashboard.scss, client/src/components/Header.js, client/src/components/Header.scss, client/src/style.scss, client/src/utils/util.js
- Header 스타일 추가 및 render 함수 구현
- Dashboard 스타일 추가 및 render 함수 구현
- Column 스타일 추가 및 render 함수 구현
- Card 스타일 추가 및 render 함수 구현
=> Header, Dashboard, Column, Card 마크업

.gitignore, server/app.js
=> Remove console log in server

client/src/components/Card.js, client/src/components/Card.scss, client/src/components/Column.js, client/src/components/Dashboard.js, client/src/components/Header.js, client/src/components/Popup.js, client/src/components/Popup.scss, client/src/utils/constants.js, client/src/utils/messages.js, client/src/utils/util.js
- 팝업  컴포넌트 스타일과 동작 구현
- utils makeElementWithClass function 인자를 객체로 넘기도록 수정
- messages.js 파일 추가
- drag and drop 실험 추가
=> 팝업 컴포넌트 추가 및 drag and drop 실험 추가

client/src/components/Card.js, client/src/components/Column.js, client/src/components/Modal.js, client/src/components/Modal.scss, client/src/components/Popup.js, client/src/components/Popup.scss, client/src/utils/messages.js, client/src/utils/util.js
- modal 스타일 추가 및 기본 기능 구현
- column, card에 modal 기능 추가
- modal에 필요한 메세지 추가
- util.js에 modal 관련 함수(show/hide)추가
=> Modal 컴포넌트 스타일 추가와 기본 기능 구현

server/DAO/cardDAO.js, server/api.http, server/app.js, server/controllers/cardController.js, server/models/Card.js, server/package-lock.json, server/package.json, server/routes/cardRouter.js, server/services/cardService.js
ISSUE: #29 
- Router, Controller, Service, DAO 레이어 추가
- GET all cards API 구현
=> Server 스켈레톤 구현

client/babel.config.js, client/package-lock.json, client/package.json, client/src/test/utils/utils.test.js, server/app.js, server/package-lock.json, server/package.json
ISSUE: #32 
- client 에서 사용하는  util함수의 BDD style의 테스트 코드를 작성했습니다.
=> Client Util 함수 단위테스트 작성

client/public/index.html, client/src/App.js, client/src/components/Header.js, client/src/components/Modal.js, client/src/components/Modal.scss, client/src/components/Popup.scss, client/src/components/Sidebar.js, client/src/components/Sidebar.scss
- Sidebar 스타일 추가 및 애니메이션 기능  구현
- Sidebar, Item scss 파일 추가
- Modal, Popup z-index 설정
- 아이콘 사용을 위해 script 추가[참고](https://ionicons.com/usage#close-outline)
애니메이션이 알고보니 css animation을 사용했네요..! 공부를 하겠습니다!
=> Sidebar 스타일 및 애니메이션 구현

client/src/components/Card.js, client/src/components/Card.scss, client/src/components/Column.js, client/src/components/Column.scss, client/src/components/Dashboard.scss, client/src/components/Header.scss, client/src/style.scss
=> 컴포넌트 스타일 수정

server/Repository/CardRepository.js, server/controllers/cardController.js, server/db.js, server/package-lock.json, server/package.json, server/routes/cardRouter.js, server/services/cardService.js, server/test/CardRepository.spec.js
- controller, service, repository 레이어를 리팩토링 했습니다.
- `XXXService` 를 class로 만들었습니다.
- `XXXRepository` 를 class 로 만들었습니다.
- `fetchAllCards()` 함수의 단위테스트를 추가했습니다.
=> Server 3 Layers 리팩토링

server/Repository/CardRepository.js, server/api.http, server/controllers/cardController.js, server/package-lock.json, server/routes/cardRouter.js, server/services/cardService.js
- cardController.js 에 getOneCard 함수 추가
- CardRepository.js 에 findCardById 함수 추가
- cardService.js 에 fetchOneCard 함수 추가
- cardRouter.js에 get `card/:id` 추가
=> GET one card api 구현

server/Repository/CardRepository.js, server/api.http, server/controllers/cardController.js, server/routes/cardRouter.js, server/services/cardService.js
- cardRouter.js에 delete card api 추가
- cardController.js에 deleteOneCard 함수 추가
- cardService.js에 removeCard 함수 추가
- CardRepository.js에 removeCardById 함수 추가
=> DELETE card api 추가

server/Repository/CardRepository.js, server/api.http, server/controllers/cardController.js, server/routes/cardRouter.js, server/services/cardService.js
- cardRouter.js에 put update card api 추가
- cardController.js에 updateCard 함수 추가
- cardService.js에 updateCard 함수 추가
- CardRepository.js에 updateCardById 함수 추가
=> PUT card api 추가

client/src/components/Dashboard.js, client/src/components/Item.js, client/src/components/Item.scss, client/src/components/Sidebar.js, client/src/components/Sidebar.scss
- Item 컴포넌트 구현
- 컴포넌트 클래안의 render함수 모듈화
=> <Item> 컴포넌트 개발

client/src/components/AddCardForm.js, client/src/components/Card.js, client/src/components/Dashboard.js, client/src/components/Modal.js, client/src/store.js
- 컬럼 제목을 변경하는 기능 추가
- 컬럼 제목 변경 시 컬럼안에 들어있는 card들의 category 값도 update
=> 컬럼 제목 수정 기능 구현

client/src/components/AddCardForm.js, client/src/components/Modal.js
AddCardForm의 textarea에 아무내용도 넣지 않으면 Add 버튼이 비활성화 되는 기능 구현
=> AddCardForm 컴포넌트 Add 버튼 비활성화 기능 구현 

client/src/services/cardService.js
이전 PR 머지하면서 놓쳤던 부분이 오류가 생겨 다시 수정하였습니다!
=> move card api 버그 수정

client/src/components/Dashboard.js
- card를 drag and drop할 때 mouseout되거나 browser에서 마우스가 벗어 났을 때 card를 원래 자리로 원복시키도록 수정
=> card drag and drop시 마우스가 벗어 났을 때 처리

client/src/components/Dashboard.js, client/src/store.js, server/repository/card-repository.js
strore.js에 moveCard 함수 오류 수정하였습니다.
=> store.js 오류 수정

client/src/components/Dashboard.js, server/controllers/card-controller.js, server/repository/card-repository.js, server/services/card-service.js
- card-controller.js에서 moveCard함수에 activityRepositoryInstance 추가
- card-service.js에서 moveCard함수에 createActivity
- Dashboard.js에서 onMouseUp에 오류 해결
=> moveCard 서비스에 activity log 추가

client/package-lock.json, client/package.json, client/src/services/activityService.js, client/src/services/cardService.js, client/src/services/columnService.js, client/src/store.js, client/webpack.common.js, server/db.js
탄력적 IP에서 발급받은 고정 IP를 사용할 수 있도록 수정
=> Client API 엔드포인트 환경변수 분리

client/src/components/Dashboard.js, client/src/components/Header.js, client/src/components/Header.scss, client/src/components/Item.scss, client/src/components/Sidebar.scss
- Header, Sidebar style 개선
- card mouseup 했을 때 error 수정
=> Header UI style 개선

README.md
=> README.md 개선

client/src/components/Dashboard.js, client/src/components/Header.js, client/src/components/Sidebar.js, client/src/store.js, server/api.http, server/app.js, server/controllers/activity-controller.js, server/controllers/card-controller.js, server/controllers/column-controller.js, server/error.js, server/public/notFound.html, server/repository/activity-repository.js, server/repository/card-repository.js, server/repository/column-repository.js, server/services/activity-service.js, server/services/card-service.js, server/services/column-service.js
각 controller들에서 `console.error()`, `res.status(404).send()` 하던 로직들을
에러처리 미들웨어에서 하도록 리팩토링
=> Server 에러 처리 리팩토링
